backend:
  name: github
  branch: master
  repo: anderskitson/website-basics-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label:"title", name: "title", widget: "string"}
      - {label:"body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}